### ISSUE TITLE
STT0021: Quality check with Vecalign for Audio-Transcript

### ISSUE THREAD

**Issue by spsither** [OpenPecha/RoBERTa#1]
### Description
Allign segment embedding and transcript embedding. Use a similarity threshold for quality checks.

### Completion Criteria
Push the pair of models to HF.

---
### Implementation Plan 
Pre-train a BERT-style encoder model for Tibetan. Fine-tune wav2vec2 and BERT-style model to align the embedding vectors.

### Subtasks
 - [ ] Pre-train RoBERTa
 - [ ] Fine-tune to align the embeddings
 - [ ] Find the similarity threshold for quality check

**Comment by spsither** [comment]
Reference [blog](https://medium.com/analytics-vidhya/create-a-tokenizer-and-train-a-huggingface-roberta-model-from-scratch-f3ed1138180c) and [code]()

**Comment by spsither** [comment]
Trained 2 tokenizers on 15GB Gold data and 45GB A

**Comment by spsither** [comment]
Filtering the A data with this function  and doing  some regex cleaning
```python
def max_char_btw_tsak(example):
    segments = example.split('་')
    max_length = max(len(segment) for segment in segments if segment)
    return max_length
```

**Comment by spsither** [comment]
Lopa says བསྒྲིགས། is the maximum valid char between tsak

Taking 8 as the filtering threshold

**Comment by spsither** [comment]
filtered the 45GB A by using the following conditions
`max_char_btw_tsak` is the max syllable  length in a sentence 
`char_len` is the character length  of the sentence

- `max_char_btw_tsak` > 1
- `max_char_btw_tsak` < 9
- `char_len` > 15
- `char_len` < 1000

**Comment by spsither** [comment]
This has A with `max_char_btw_tsak` and `char_len` metadata
https://huggingface.co/datasets/spsither/tibetan_monolingual_A_meta

Filtered A is at 
https://huggingface.co/datasets/spsither/tibetan_monolingual_A_filtered

Filtered and Deduped A on sentence is at
https://huggingface.co/datasets/spsither/tibetan_monolingual_A_filtered_deduped

**Comment by spsither** [comment]
using pandas to drop duplicates in filtered A

**Comment by spsither** [comment]
| Action                    | Train size    | Test size    | % drop |
|--------------------------|-----------------|----------------|-----------|
| Original                  |  335968205 | 18500104 | 0           |
| Filtered                  |  293280837 | 16162978  | 12.7     |
| Dedupe + Filtered |   93214402  |  11561844 | 70.4      |

45GB  -> 18GB

**Comment by spsither** [comment]
data is still not clean 
bad tokens examples

- དགའཁས
- གནསབདག
- དངབཅསཔདང
- སསསསསསསས
- བབབབབབབབ

**Comment by spsither** [comment]
Started training RoBERTa Large on 18GB [A_filtered_deduped](https://huggingface.co/datasets/spsither/tibetan_monolingual_A_filtered_deduped) data at Apr 26th 4:50 PM Using `ml.g5.4xlarge`

**Comment by spsither** [comment]
![Image](https://github.com/OpenPecha/RoBERTa/assets/11909317/34aad24d-7e04-4b87-80e6-a6558f89b200)

**Comment by spsither** [comment]
Most of the text data we have is about Buddhism, might be good to use these for training

https://huggingface.co/datasets/oscar-corpus/OSCAR-2201

https://huggingface.co/datasets/oscar-corpus/OSCAR-2301

**Comment by kaldan007** [comment]
https://zenodo.org/records/3951503

**Comment by spsither** [comment]
Word Segmentation data from Marieke is [here](https://huggingface.co/datasets/spsither/tibetan_monolingual_SegPOS)

**Comment by spsither** [comment]
I used Botok to filter out sentences with any bad tokens. We now have 16GB of text data. The dataset is [here](https://huggingface.co/datasets/spsither/tibetan_monolingual_S_cleaned_train_test). This dataset consists of the following
 - [Monolingual A](https://huggingface.co/datasets/spsither/tibetan_monolingual_A_filtered_deduped)
 - OSCAR [22](https://huggingface.co/datasets/oscar-corpus/OSCAR-2201) and [23](https://huggingface.co/datasets/oscar-corpus/OSCAR-2301)
 - [Segmentation data from Marieke](https://huggingface.co/datasets/spsither/tibetan_monolingual_SegPOS)
 - [Bhangchen](https://github.com/TenzinGayche/bot/blob/master/tsv/bangchen.tsv)

**Comment by spsither** [comment]
https://huggingface.co/spsither/tibetan_RoBERTa_S_e2

**Comment by spsither** [comment]
refer [this](https://dcase.community/documents/challenge2022/technical_reports/DCASE2022_Weck_21_t6b.pdf) paper
![Image](https://github.com/OpenPecha/RoBERTa/assets/11909317/d0702e15-1f06-4ba4-9f49-be5f6434be5b)

**Comment by spsither** [comment]
model at epoch 6 is [here](https://huggingface.co/openpecha/tibetan_RoBERTa_S_e6)

**Comment by spsither** [comment]
The default trainer API uses DP instead of DDP. I am reading up [accelerate](https://huggingface.co/docs/accelerate/en/index) so we can use DDP or more advanced techniques.

**Comment by spsither** [comment]
Referencing [t5](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation_no_trainer.py), [bert](https://github.com/philschmid/deep-learning-pytorch-huggingface/blob/main/training/accelerate-tpu-bert-text-classification.ipynb) and [roberta](https://www.kaggle.com/code/pukkinming/lecr-xlm-roberta-base-accelerate-multi-gpu) for using accelerate.
